# window swallow 
alias vlc='ws vlc'
alias zathura='ws zathura'
alias mpv='ws mpv'



alias ll='exa'
alias l='exa -al'
alias la='exa -a'
alias pacin='sudo pacman -S'
alias gita='git add'
alias gitc='git commit'
alias ra='ranger'
alias r='joshuto'
alias paclean='sudo pacman -Sc'
alias pacu='sudo pacman -Rns'
alias gitp='git push'
alias c='clear'
alias s='neofetch'
alias cat='bat'
alias za='ws zathura'
alias pacman='sudo pacman'
alias nb='newsboat'
alias lg='lazygit'
alias cbg='cd ~/.local/blog/MasterJ/source/_posts/'
